version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

  jobs:
    post_create_environment:
      - pip install poetry
      - poetry config virtualenvs.create false
    post_install:
      - poetry install --with docs --without opengl
      - pip list
      - poetry show

sphinx:
  configuration: docs/source/conf.py