version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

  jobs:
    post_install:
      - pip install uv
      - UV_PROJECT_ENVIRONMENT=$READTHEDOCS_VIRTUALENV_PATH uv sync --all-extras --link-mode=copy
    
sphinx:
  configuration: docs/source/conf.py
