version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

  jobs:
    post_create_environment:
      - pip install poetry
    post_install:
      - poetry install --with docs --without opengl
      - poetry shell

sphinx:
  configuration: docs/source/conf.py