name: Publish to TestPyPI using Poetry

on:
  push:
    tags:
      - v*        # trigger when a tag starts with 'v'
    branches:
      - master    # only on the master branch
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    environment:
      name: testpypi
      url: https://test.pypi.org/p/openwfs
      
    permissions:
      id-token: write  # Required for OIDC
    
    steps:
    # Checkout the repository
    - name: Check out the repository
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Install Poetry
    - name: Install Poetry
      uses: abatilo/actions-poetry@v2
      with:
        version: '1.8.3'
        
    # Install dependencies and build the project
    - name: Install dependencies and build package
      run: |
        poetry install
        poetry build

    - name: Publish package distributions to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        verbose: true
        
